app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('/','IndexController',[
									'only' =>['index'],
									'names' => [
										'index'=>'home'
									]
									]);								

Route::resource('portfolios','PortfolioController',[
													
													'parameters' => [
													
														'portfolios' => 'alias'
													
													]
													
													]);

Route::resource('articles','ArticlesController',[
												
												'parameters'=>[
												
													'articles' => 'alias'
												
												]
												
												]);	
Route::get('articles/cat/{cat_alias?}',['uses'=>'ArticlesController@index','as'=>'articlesCat'])->where('cat_alias','[\w-]+');   


Route::resource('comment','CommentController',['only'=>['store']]);

Route::match(['get','post'],'/contacts',['uses'=>'ContactsController@index','as'=>'contacts']);

//php artisan make:auth
Route::get('login','Auth\AuthController@showLoginForm');

Route::post('login','Auth\AuthController@login');

Route::get('logout','Auth\AuthController@logout');


//admin
Route::group(['prefix' => 'admin','middleware'=> 'auth'],function() {
	
	//admin
	Route::get('/',['uses' => 'Admin\IndexController@index','as' => 'adminIndex']);
	
	// articles
	Route::resource('/articles','Admin\ArticlesController');
	
	Route::resource('/permissions','Admin\PermissionsController');
	
	Route::resource('/menus','Admin\MenusController');
	
});



																						

resources/views/pink/admin/articles.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
	{!! $navigation !!}
@endsection

@section('content')
	{!! $content !!}
@endsection

@section('footer')
	{!! $footer !!}
@endsection 

resources/views/pink/admin/articles_content.blade.php
@if($articles)
	<div id="content-page" class="content group">
				            <div class="hentry group">
				                <h2>Добавленные статьи</h2>
				                <div class="short-table white">
				                    <table style="width: 100%" cellspacing="0" cellpadding="0">
				                        <thead>
				                            <tr>
				                                <th class="align-left">ID</th>
				                                <th>Заголовок</th>
				                                <th>Текст</th>
				                                <th>Изображение</th>
				                                <th>Категория</th>
				                                <th>Псевдоним</th>
				                                <th>Дествие</th>
				                            </tr>
				                        </thead>
				                        <tbody>
				                            
											@foreach($articles as $article)
											<tr>
				                                <td class="align-left">{{$article->id}}</td>
				                                <td class="align-left">{!! Html::link(route('admin.articles.edit',['articles'=>$article->alias]),$article->title) !!}</td>
				                                <td class="align-left">{{str_limit($article->text,200)}}</td>
				                                <td>
													@if(isset($article->img->mini))
													{!! Html::image(asset(env('THEME')).'/images/articles/'.$article->img->mini) !!}
													@endif
												</td>
				                                <td>{{$article->category->title}}</td>
				                                <td>{{$article->alias}}</td>
				                                <td>
												{!! Form::open(['url' => route('admin.articles.destroy',['articles'=>$article->alias]),'class'=>'form-horizontal','method'=>'POST']) !!}
												    {{ method_field('DELETE') }}
												    {!! Form::button('Удалить', ['class' => 'btn btn-french-5','type'=>'submit']) !!}
												{!! Form::close() !!}
												</td>
											 </tr>	
											@endforeach	
				                           
				                        </tbody>
				                    </table>
				                </div>
								
								{!! HTML::link(route('admin.articles.create'),'Добавить  материал',['class' => 'btn btn-the-salmon-dance-3']) !!}
                                
				                
				            </div>
				            <!-- START COMMENTS -->
				            <div id="comments">
				            </div>
				            <!-- END COMMENTS -->
				        </div>
@endif

resources/views/pink/admin/articles_create_content.blade.php
<div id="content-page" class="content group">
				            <div class="hentry group">

{!! Form::open(['url' => (isset($article->id)) ? route('admin.articles.update',['articles'=>$article->alias]) : route('admin.articles.store'),'class'=>'contact-form','method'=>'POST','enctype'=>'multipart/form-data']) !!}
    
	<ul>
		<li class="text-field">
			<label for="name-contact-us">
				<span class="label">Название:</span>
				<br />
				<span class="sublabel">Заголовок материала</span><br />
			</label>
			<div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
			{!! Form::text('title',isset($article->title) ? $article->title  : old('title'), ['placeholder'=>'Введите название страницы']) !!}
			 </div>
		 </li>
		 
		 <li class="text-field">
			<label for="name-contact-us">
				<span class="label">Ключевые слова:</span>
				<br />
				<span class="sublabel">Заголовок материала</span><br />
			</label>
			<div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
			{!! Form::text('keywords', isset($article->keywords) ? $article->keywords  : old('keywords'), ['placeholder'=>'Введите название страницы']) !!}
			 </div>
		 </li>
		 
		 <li class="text-field">
			<label for="name-contact-us">
				<span class="label">Мета описание:</span>
				<br />
				<span class="sublabel">Заголовок материала</span><br />
			</label>
			<div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
			{!! Form::text('meta_desc', isset($article->meta_desc) ? $article->meta_desc  : old('meta_desc'), ['placeholder'=>'Введите название страницы']) !!}
			 </div>
		 </li>
		 
		 <li class="text-field">
			<label for="name-contact-us">
				<span class="label">Псевдоним:</span>
				<br />
				<span class="sublabel">введите псевдоним</span><br />
			</label>
			<div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
			{!! Form::text('alias', isset($article->alias) ? $article->alias  : old('alias'), ['placeholder'=>'Введите псевдоним страницы']) !!}
			 </div>
		 </li>
		 
		 <li class="textarea-field">
			<label for="message-contact-us">
				 <span class="label">Краткое описание:</span>
			</label>
			<div class="input-prepend"><span class="add-on"><i class="icon-pencil"></i></span>
			{!! Form::textarea('desc', isset($article->desc) ? $article->desc  : old('desc'), ['id'=>'editor','class' => 'form-control','placeholder'=>'Введите текст страницы']) !!}
			</div>
			<div class="msg-error"></div>
		</li>
		
		<li class="textarea-field">
			<label for="message-contact-us">
				 <span class="label">Описание:</span>
			</label>
			<div class="input-prepend"><span class="add-on"><i class="icon-pencil"></i></span>
			{!! Form::textarea('text', isset($article->text) ? $article->text  : old('text'), ['id'=>'editor2','class' => 'form-control','placeholder'=>'Введите текст страницы']) !!}
			</div>
			<div class="msg-error"></div>
		</li>
		
		@if(isset($article->img->path))
			<li class="textarea-field">
				
				<label>
					 <span class="label">Изображения материала:</span>
				</label>
				
				{{ Html::image(asset(env('THEME')).'/images/articles/'.$article->img->path,'',['style'=>'width:400px']) }}
				{!! Form::hidden('old_image',$article->img->path) !!}
			
				</li>
		@endif
		
		
		<li class="text-field">
			<label for="name-contact-us">
				<span class="label">Изображение:</span>
				<br />
				<span class="sublabel">Изображение материала</span><br />
			</label>
			<div class="input-prepend">
				{!! Form::file('image', ['class' => 'filestyle','data-buttonText'=>'Выберите изображение','data-buttonName'=>"btn-primary",'data-placeholder'=>"Файла нет"]) !!}
			 </div>
			 
		</li>
		
		<li class="text-field">
			<label for="name-contact-us">
				<span class="label">Категория:</span>
				<br />
				<span class="sublabel">Категория материала</span><br />
			</label>
			<div class="input-prepend">
				{!! Form::select('category_id', $categories,isset($article->category_id) ? $article->category_id  : '') !!}
			 </div>
			 
		</li>	 
		
		@if(isset($article->id))
			<input type="hidden" name="_method" value="PUT">		
		
		@endif

		<li class="submit-button"> 
			{!! Form::button('Сохранить', ['class' => 'btn btn-the-salmon-dance-3','type'=>'submit']) !!}			
		</li>
		 
	</ul>
	
    
    
    
    
{!! Form::close() !!}

 <script>
	CKEDITOR.replace( 'editor' );
	CKEDITOR.replace( 'editor2' );
</script>
</div>
</div>

resources/views/pink/admin/custom-menu-items.blade.php
@foreach($items as $item)

		<tr>
			<td style="text-align: left;">{{ $paddingLeft }} {!! Html::link(route('admin.menus.edit',['menus' => $item->id]),$item->title) !!}</td>
			<td>{{ $item->url() }}</td>

			<td>
			{!! Form::open(['url' => route('admin.menus.destroy',['menus'=> $item->id]),'class'=>'form-horizontal','method'=>'POST']) !!}
												    {{ method_field('DELETE') }}
												    {!! Form::button('Удалить', ['class' => 'btn btn-french-5','type'=>'submit']) !!}
												{!! Form::close() !!}

			</td>
		</tr>		
		 @if($item->hasChildren())
		        
		        @include(env('THEME').'.admin.custom-menu-items', array('items' => $item->children(),'paddingLeft' => $paddingLeft.'--'))

		 @endif

@endforeach

resources/views/pink/admin/footer.blade.php
<div id="copyright">
                    <div class="inner group">
                        <div class="left">
                            <a href="http://yithemes.com/?ddownload=2046&ap_id=pinkrio-html"><strong>Download the free version for Wordpress</strong></a>
                        </div>
                        <div class="right">
                            <a href="#" class="socials-small facebook-small" title="Facebook">facebook</a>
                            <a href="#" class="socials-small rss-small" title="Rss">rss</a>
                            <a href="#" class="socials-small twitter-small" title="Twitter">twitter</a>
                            <a href="#" class="socials-small flickr-small" title="Flickr">flickr</a>
                            <a href="#" class="socials-small skype-small" title="Skype">skype</a>
                            <a href="#" class="socials-small google-small" title="Google">google</a>
                            <a href="#" class="socials-small pinterest-small" title="Pinterest">pinterest</a>
                        </div>
                    </div>
                </div>

resources/views/pink/admin/index.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
	{!! $navigation !!}
@endsection

@section('footer')
	{!! $footer !!}
@endsection 

resources/views/pink/admin/menus.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
	{!! $navigation !!}
@endsection

@section('content')
	{!! $content !!}
@endsection

@section('footer')
	{!! $footer !!}
@endsection 

resources/views/pink/admin/menus_content.blade.php
<div id="content-page" class="content group">
				            <div class="hentry group">
<h3 class="title_page">Пользователи</h3>


<div class="short-table white">
	<table style="width: 100%" cellspacing="0" cellpadding="0">
	<thead>
		
		<th>Name</th>
		<th>Link</th>
		
		<th>Удалить</th>
	</thead>
	@if($menus)
	
		@include(env('THEME').'.admin.custom-menu-items', array('items' => $menus->roots(),'paddingLeft' => ''))
		
		
	@endif
	</table>
	</div>
	{!! HTML::link(route('admin.menus.create'),'Добавить  пункт',['class' => 'btn btn-the-salmon-dance-3']) !!}
	
</div>
</div>

resources/views/pink/admin/menus_create_content.blade.php
<div id="content-page" class="content group">
				            <div class="hentry group">

{!! Form::open(['url' => (isset($menu->id)) ? route('admin.menus.update',['menus'=>$menu->id]) : route('admin.menus.store'),'class'=>'contact-form','method'=>'POST','enctype'=>'multipart/form-data']) !!}
    
	<ul>
		
		<li class="text-field">
			<label for="name-contact-us">
				<span class="label">Заголовок:</span>
				<br />
				<span class="sublabel">Заголовок пункта</span><br />
			</label>
			<div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
			{!! Form::text('title',isset($menu->title) ? $menu->title  : old('title'), ['placeholder'=>'Введите название страницы']) !!}
			 </div>
		 </li>
		
		
		<li class="text-field">
			<label for="name-contact-us">
				<span class="label">Родительский пункт меню:</span>
				<br />
				<span class="sublabel">Родитель:</span><br />
			</label>
			<div class="input-prepend">
				{!! Form::select('parent', $menus, isset($menu->parent) ? $menu->parent : null) !!}
			 </div>
			 
		</li>
	</ul>	
		
		<h1">Тип меню:</h1>
		
		<div id="accordion">
		
		<h3>{!! Form::radio('type', 'customLink',(isset($type) && $type == 'customLink') ? TRUE : FALSE,['class' => 'radioMenu']) !!}	
			<span class="label">Пользовательская ссылка:</span></h3>
			
			<ul>
			
				<li class="text-field">
					<label for="name-contact-us">
						<span class="label">Путь для ссылки:</span>
						<br />
						<span class="sublabel">Путь для ссылки</span><br />
					</label>
					<div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
					{!! Form::text('custom_link',(isset($menu->path) && $type=='customLink') ? $menu->path  : old('custom_link'), ['placeholder'=>'Введите название страницы']) !!}
					 </div>
				</li>
			<div style="clear: both;"></div>
			</ul>
			
			
			<h3>{!! Form::radio('type', 'blogLink',(isset($type) && $type == 'blogLink') ? TRUE : FALSE,['class' => 'radioMenu']) !!}	
			<span class="label">Раздел Блог:</span></h3>
			
			<ul>
			
				<li class="text-field">
					<label for="name-contact-us">
						<span class="label">Ссылка на категорию блога:</span>
						<br />
						<span class="sublabel">Ссылка на категорию блога</span><br />
					</label>
					<div class="input-prepend">
						
						@if($categories)
						{!! Form::select('category_alias',$categories,(isset($option) && $option) ? $option :FALSE) !!}
						@endif
					</div>
				</li>
			
				
				<li class="text-field">
					<label for="name-contact-us">
						<span class="label">Ссылка на материал блога:</span>
						<br />
						<span class="sublabel">Ссылка на материал блога</span><br />
					</label>
					<div class="input-prepend">
					{!! Form::select('article_alias', $articles, (isset($option) && $option) ? $option :FALSE, ['placeholder' => 'Не используется']) !!}
			
					</div>
					 
				</li>	 
			<div style="clear: both;"></div>
			</ul>
			
			
			
			<h3>{!! Form::radio('type', 'portfolioLink',(isset($type) && $type == 'portfolioLink') ? TRUE : FALSE,['class' => 'radioMenu']) !!}	
			<span class="label">Раздел портфолио:</span></h3>
			
			<ul>
			
				<li class="text-field">
					<label for="name-contact-us">
						<span class="label">Ссылка на запись портфолио:</span>
						<br />
						<span class="sublabel">Ссылка на запись портфолио</span><br />
					</label>
					<div class="input-prepend">
					{!! Form::select('portfolio_alias', $portfolios, (isset($option) && $option) ? $option :FALSE, ['placeholder' => 'Не используется']) !!}
			
					</div>
					 
				</li>
				
				<li class="text-field">
					<label for="name-contact-us">
						<span class="label">Портфолио:</span>
						<br />
						<span class="sublabel">Портфолио</span><br />
					</label>
					<div class="input-prepend">
					{!! Form::select('filter_alias', $filters, (isset($option) && $option) ? $option :FALSE, ['placeholder' => 'Не используется']) !!}
			
					</div>
					 
				</li>
				
			
			</ul>
			
			
			
		</div>
		
		<br />
		
		@if(isset($menu->id))
			<input type="hidden" name="_method" value="PUT">		
		
		@endif
		<ul>
			<li class="submit-button"> 
						{!! Form::button('Сохранить', ['class' => 'btn btn-the-salmon-dance-3','type'=>'submit']) !!}			
			</li>	
		</ul>
		 
	
	
    
    
    
    
{!! Form::close() !!}


</div>
</div>

<script>
	
	jQuery(function($) {
		
		$('#accordion').accordion({
			
			activate: function(e, obj) {
				obj.newPanel.prev().find('input[type=radio]').attr('checked','checked');
			}
				
		});
		
	})
	
</script>

resources/views/pink/admin/navigation.blade.php
@if($menu)
	<div class="menu classic">
		
		{!! $menu->asUl(['class'=>'menu']) !!}
		
	</div>
@endif

resources/views/pink/admin/permissions.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
	{!! $navigation !!}
@endsection

@section('content')
	{!! $content !!}
@endsection

@section('footer')
	{!! $footer !!}
@endsection 

resources/views/pink/admin/permissions_content.blade.php
<div id="content-page" class="content group">
	<div class="hentry group">
	
	<h3 class="title_page">Привилегии</h3>
	
	<form action="{{ route('admin.permissions.store') }}" method="POST">
		{{ csrf_field() }}
		
		<div class="short-table white">
		
			<table style="width:100%">
				
				<thead>
					
					<th>Привилегии</th>
					@if(!$roles->isEmpty())
					
						@foreach($roles as $item)
							<th>{{ $item->name}}</th>
						@endforeach
					
					@endif
					
				</thead>
				<tbody>
					
					@if(!$priv->isEmpty())
					
						@foreach($priv as $val)
							<tr>
								
								<td>{{ $val->name }}</td>
									@foreach($roles as $role)
										<td>
											@if($role->hasPermission($val->name))
												<input checked name="{{ $role->id }}[]"  type="checkbox" value="{{ $val->id }}">
											@else
												<input name=" {{ $role->id }}[]"  type="checkbox" value="{{ $val->id }}">
											@endif	
										</td>
									@endforeach
							</tr>
						@endforeach
					
					@endif

				</tbody>
				
				
			</table>
			
			
		</div>
		
		<input class="btn btn-the-salmon-dance-3" type="submit" value="Обновить" />

		
	</form>

	
	</div>
</div>